packages:
  - 'apps/*'
  - 'packages/*'
  - 'prod/sst'
  - 'scripts'
  - 'tools/*'
allowBuilds:
  '@prisma/engines': true
  '@rocicorp/zero-sqlite3': true
  core-js: false
  core-js-pure: false
  cpu-features: false
  esbuild: true
  prisma: true
  protobufjs: true
  ssh2: false
minimumReleaseAgeExclude:
  - playwright@1.55.1
  - minimatch@10.2.1
  - minimatch@10.2.3
  - serialize-javascript@7.0.3
  - undici@6.24.0
  - lodash@4.17.24
  - ajv@8.18.0
  - '@hono/node-server@1.19.13'
  - postcss@8.5.10
  - '@rocicorp/zero-sqlite3'
  - '@rocicorp/logger@6.1.0'
  - '@rocicorp/zero-virtual@0.6.3'

overrides:
  '@hono/node-server@<1.19.13': ^1.19.13
  '@types/node': '^22.10.5'
  ajv@>=7.0.0-alpha.0 <8.18.0: ^8.18.0
  esbuild: '0.27.7'
  lodash@>=4.0.0 <=4.17.23: ^4.17.24
  minimatch@>=10.0.0 <10.2.1: ^10.2.1
  minimatch@>=10.0.0 <10.2.3: ^10.2.3
  playwright@<1.55.1: ^1.55.1
  postcss@<8.5.10: ^8.5.10
  serialize-javascript@<=7.0.2: ^7.0.3
  undici@<6.24.0: ^6.24.0
  webpackbar: ^7.0.0

patchedDependencies:
  postgres@3.4.7: packages/zero/patches/postgres@3.4.7.patch
