export const SERIALIZABLE = 'ISOLATION LEVEL SERIALIZABLE';
export const READ_COMMITTED = 'ISOLATION LEVEL READ COMMITTED';
export const READONLY = 'ISOLATION LEVEL REPEATABLE READ READ ONLY';

export type SERIALIZABLE = typeof SERIALIZABLE;
export type READ_COMMITTED = typeof READ_COMMITTED;
export type READONLY = typeof READONLY;
