// This file defines a complex query to stress test TypeScript's type
// inference and the Zero query builder: 90 distinct .related() calls
// on workspace table to test wide query result types
//
// We also export the query and Zero instance so that tsc will try to compile it
// and fail if it can't output .d.ts

import {zeroStress} from './zero-stress-client-test.ts';

const queryWide = zeroStress.query.workspace
  .related('sessions')
  .related('accounts')
  .related('workspaceMembers')
  .related('teams')
  .related('apiKeys')
  .related('verificationTokens')
  .related('passwordResets')
  .related('auditLogs')
  .related('entityTags')
  .related('entityAttachments')
  .related('entityComments')
  .related('customFieldDefinitions')
  .related('customFieldValues')
  .related('webhooks')
  .related('webhookDeliveries')
  .related('rateLimits')
  .related('featureFlags')
  .related('integrations')
  .related('emailCampaigns')
  .related('emailTemplates')
  .related('emailSends')
  .related('subscriberLists')
  .related('subscribers')
  .related('automationWorkflows')
  .related('emailLinks')
  .related('unsubscribeEvents')
  .related('emailAttachments')
  .related('spamComplaints')
  .related('ticketMessages')
  .related('knowledgeBaseArticles')
  .related('slaPolicies')
  .related('cannedResponses')
  .related('supportTickets')
  .related('ticketTags')
  .related('satisfactionSurveys')
  .related('agentAssignments')
  .related('ticketEscalations')
  .related('ticketMerges')
  .related('products')
  .related('productVariants')
  .related('orders')
  .related('orderLineItems')
  .related('shoppingCarts')
  .related('productReviews')
  .related('inventoryAdjustments')
  .related('discountCodes')
  .related('shippingZones')
  .related('paymentTransactions')
  .related('cmsArticles')
  .related('cmsPages')
  .related('mediaAssets')
  .related('contentRevisions')
  .related('taxonomyTerms')
  .related('contentBlocks')
  .related('cmsMenus')
  .related('redirectRules')
  .related('cmsComments')
  .related('contentLocks')
  .related('projects')
  .related('tasks')
  .related('taskDependencies')
  .related('sprints')
  .related('boards')
  .related('timeEntries')
  .related('taskComments')
  .related('milestones')
  .related('projectBudgets')
  .related('resourceAllocations')
  .related('employees')
  .related('payrollRuns')
  .related('payrollLines')
  .related('timeOffRequests')
  .related('benefitsEnrollments')
  .related('performanceReviews')
  .related('departments')
  .related('compensationChanges')
  .related('trainingRecords')
  .related('attendanceLogs')
  .related('ledgerAccounts')
  .related('journalEntries')
  .related('journalLines')
  .related('invoices')
  .related('payments')
  .related('bankTransactions')
  .related('expenseClaims')
  .related('budgets')
  .related('taxRates')
  .related('reconciliations')
  .related('patients')
  .related('appointments');

// this is testing .d.ts generation for complex queries
export {queryWide};
